### PR TITLE
Introduce Akka.Discovery.AwsApi package

### PR DESCRIPTION
**Pull request by Arkatufus**

### CODE REVIEW

**Comment by Arkatufus** [comment]
@Aaronontheweb I'm not sure if this is the correct way of doing this, can you give this a check?

**Review by Aaronontheweb — CHANGES_REQUESTED** [review]
LGTM - can you please add a detailed `README.md` in this directory which explains how to use this plugin?

**Comment by Arkatufus** [comment]
Will add the README.md and documentations, and most probably change the ECS discovery to internal so no one uses it

**Comment by Aaronontheweb** [comment]
Looks good to me

**Review by Aaronontheweb — APPROVED** [review]

**Pull request merged**
