### PR TITLE
[AWS.EC2] Add Settings and Setup class

### PR DESCRIPTION
**Pull request by Arkatufus**
## Breaking Change
Changed the `akka.discovery.aws-api-ec2-tag-based.credentials-provider` HOCON setting from a HOCON path to FQCN instead

### CODE REVIEW

**Comment by Arkatufus** [comment]
Marked as draft because of the breaking change, wanted to make sure that this is OK

**Review by Aaronontheweb — APPROVED** [review]

**Review by Aaronontheweb — CHANGES_REQUESTED** [review]
We should detect after we parse the change-breaking setting if the user is still using an old value - if so we should throw an exception and force them to update.

**Comment by Arkatufus** [comment]
Done, added a verbose exception message and documented it in the code.

**Review by Aaronontheweb — APPROVED** [review]

**Review by Aaronontheweb — APPROVED** [review]
LGTM

**Pull request merged**
